- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: Linux , shell , Ansible , Terraform
  tasks:
  - name: convert string to linux
    debug:
      msg: "Topics are: {{ topics | split(',') }}"    