- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: Linux , shell , Ansible , Terraform
    tagmap: 
     name: Ansible
     project: roboshop
     environment: dev
  tasks:
  - name: convert string to linux
    debug:
      msg: "Topics are: {{ topics | split( ',' ) }}" 

  - name: set value
    debug:
      msg: " Hi {{ Greeting | default('Good Morning') }}" 


  - name: convert map to list
    debug:
     msg: "{{ tagmap | dict2list }}"            